modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Curios/issues"
logoFile="curios_icon.png"
[[mods]]
modId="curios"
version="${file.jarVersion}"
displayName="Curios API"
displayURL="https://minecraft.curseforge.com/projects/curios"
authors="C4"
description='''
A flexible and expandable accessory/equipment API for users and developers.
'''
[[dependencies.curios]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"